accounts/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views

from .views import (
    AccountDashboardView,
    AccountActivateView,
    LoginView,
    RegisterView,
    DoneRegisterView,
    UserDetailUpdateView,
    UserPasswordChangeView,
)

urlpatterns = [
    url(r'^dashboard/$', AccountDashboardView.as_view(), name='dashboard'),
    url(r'^login/$', LoginView.as_view(), name='login'),
    url(r'^logout/$', auth_views.logout, name='logout'),
    url(r'^register/$', RegisterView.as_view(), name='register'),
    url(r'^register/done/$', DoneRegisterView.as_view(), name='register_done'),
    url(r'^activate/(?P<uidb64>[0-9A-Za-z]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        AccountActivateView.as_view(), name='activate'),
    url(r'^password/$', UserPasswordChangeView.as_view(), name='change_password'),
    url(r'^details/$', UserDetailUpdateView.as_view(), name='user-update'),

    # Password Reset View
    url(r'^password_reset/$',
        auth_views.password_reset, {
            'template_name': 'password_reset/password_reset_form.html',
            'email_template_name': 'password_reset/password_reset_email.html',
            'subject_template_name': 'password_reset/password_reset_subject.txt',
            'post_reset_redirect': 'accounts:password_reset_done',
        },
        name='password_reset'),

    url(r'^password_reset/done/$', auth_views.password_reset_done, {
        'template_name': 'password_reset/password_reset_done.html',
        },
        name='password_reset_done'),

    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        auth_views.password_reset_confirm, {
            'template_name': 'password_reset/password_reset_confirm.html',
            'post_reset_redirect': 'accounts:password_reset_complete',
        },
        name='password_reset_confirm'),

    url(r'^reset/done/$', auth_views.password_reset_complete, {
        'template_name': 'password_reset/password_reset_complete.html',
        },
        name='password_reset_complete')
]

company/api/urls.py
from django.conf.urls import url

from .views import CompanyListAPIView, SessionAPIView

urlpatterns = [
    url(r'^(?P<pk>\d+)/$', SessionAPIView.as_view(), name='favorite'),
    url(r'^list/$', CompanyListAPIView.as_view(), name='company_list'),
]

company/urls.py
from django.conf.urls import url

from .views import (
    CompanyListView,
    CompanyAddView,
    CompanyDetailView,
    CompanyUpdateView,
    CompanyDeleteView,
    # CompanyCreate
)

urlpatterns = [
    # url(r'^$', CompanyListView.as_view(), name='companies'),
    url(r'^filter/(?P<location>[a-z\-]+)?/?(?P<type>[a-z\-]+)?/?(?P<price>[a-z0-9\-]+)?/?$', CompanyListView.as_view(), name='companies'),
    # url(r'^toaster/$', CompanyListView.as_view(), name='companies'),
    url(r'^add/$', CompanyAddView.as_view(), name='company_add'),
    # url(r'^add/$', CompanyCreate.as_view(), name='company_add'),
    url(r'^update/(?P<pk>\d+)/$', CompanyUpdateView.as_view(), name='company_update'),
    url(r'^delete/(?P<pk>\d+)/$', CompanyDeleteView.as_view(), name='company_delete'),
    url(r'^(?P<pk>\d+)/$', CompanyDetailView.as_view(), name='company_detail'),
    # url(r'^profile_update/$', ProfileCreateView.as_view(), name='profile-update'),
]

core/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf.urls.static import static

import django.views.static
from django.conf import settings


urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^ckeditor/', include('ckeditor_uploader.urls')),
    # url(r'^toasters/', include('toast.urls', namespace='toast')),
    url(r'^company/', include('company.urls', namespace='company')),
    url(r'^tags/', include('tags.urls', namespace='tags')),
    url(r'gallery/', include('gallery.urls', namespace='gallery')),

    url(r'^media/(?P<path>.*)$', django.views.static.serve, {'document_root': settings.MEDIA_ROOT}),

    url(r'^accounts/', include('accounts.urls', namespace='accounts')),

    url(r'^api/v1/company/', include('company.api.urls', namespace='api_company')),
    url(r'^api/v1/gallery/', include('gallery.api.urls', namespace='api_gallery'))
]

# if settings.DEBUG:
#     if settings.MEDIA_URL:
#         urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_URL)
#         urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

gallery/urls.py
from django.conf.urls import url

from .views import (
    AlbumListView,
    PhotoListView,
    PhotoAddView,
    AlbumAddView,
    AlbumUpdateView,
    AlbumDeleteView,

    PhotosListView,
)


urlpatterns = [
    url(r'^albums/$', AlbumListView.as_view(), name='albums'),
    url(r'^album/(?P<pk>\d+)/$', PhotoListView.as_view(), name='photo'),
    url(r'^photo-add/$', PhotoAddView.as_view(), name='photo_add'),
    url(r'^album/add/$', AlbumAddView.as_view(), name='album_add'),
    url(r'^album/(?P<pk>\d+)/update/$', AlbumUpdateView.as_view(), name='album_update'),
    url(r'^album/(?P<pk>\d+)/delete/$', AlbumDeleteView.as_view(), name='album_delete'),

    url(r'^photos/$', PhotosListView.as_view(), name='photos'),

    # url(r'^add/$', CompanyAddView.as_view(), name='company_add'),
    # url(r'^update/(?P<pk>\d+)/$', CompanyUpdateView.as_view(), name='company_update'),
    # url(r'^delete/(?P<pk>\d+)/$', CompanyDeleteView.as_view(), name='company_delete'),
    # url(r'^(?P<pk>\d+)/$', CompanyDetailView.as_view(), name='company_detail'),
    # url(r'^profile_update/$', ProfileCreateView.as_view(), name='profile-update'),
]

templates/core/include/footer.html
{% load i18n %}
<footer style="visibility:hidden;">
    <div class="grid-x grid-margin-x grid-margin-y">
        <div class="cell small-12 medium-3 large-2 footer-logo">
            <a class="" href="{% url 'company:companies' %}">TOASTERS</a>
        </div>
        <div class="cell small-12 medium-3 large-3 grid-x grid-y grid-margin-y">
            <a class="" href="#">О ПРОЕКТЕ</a>
            <a class="" href="#">About</a>
            <a class="" href="#">Contact</a>
            <a class="" href="{% url 'accounts:register' %}">
                {% trans 'Registration for specialists' %}</a>
            <p>Copyright 2018</p>
        </div>
        <div class="cell small-12 medium-3 large-3 grid-x grid-y grid-margin-y">
            <a href="#">Home</a>
            <a href="#">About</a>
            <a href="#">Contact</a>
            <a class="" href="{% url 'accounts:register' %}">
                {% trans 'Registration for specialists'|upper %}</a>
            <p>Copyright 2018</p>
        </div>
    </div>
</footer>

templates/core/include/messages.html
<div class="row ">

<div class="alert-box">
{% for message in messages %}
    <div data-closable class="callout {{ message.tags }}">
        {% if message.tags == 'alert' %}
            <i class="fas fa-exclamation-circle fa-lg" style="font-size: 2rem;"></i>
        {% elif message.tags == 'success' %}
            <i class="fa fa-check-circle fa-lg" style="font-size: 2rem;"></i>
        {% endif %}
        &nbsp;{{ message }}
        <button class="close-button" aria-label="Dismiss alert" type="button" data-close>
            <i class="far fa-times-circle"></i>
        </button>
    </div>
{% endfor %}
</div>
</div>

templates/core/include/modal_fav.html
<div class="large reveal" id="getFavorites" data-reveal>
    <h1>Favorites</h1>
    <div id="companyFav" class="grid-x grid-margin-y"></div>
    <button class="close-button" data-close aria-label="Close modal" type="button">
        <span aria-hidden="true">&times;</span>
    </button>
</div>

templates/core/include/modal_gallery.html
<!-- Gallery/Albums List -->
{% load i18n %}

<div class="large reveal" id="getGallery" data-reveal>
    <h3>{% trans "Albums list" %}</h3>

{#    <div id="" class="grid-x grid-margin-y">#}
        {# CARDS #}
        <div class="grid-x grid-margin-x grid-margin-y align-left">
            {% for album in albums %}
                <div class="cell small-12 medium-4 large-3">
                    <div class="thumbnail card " style="height: 100%; width: 100%;">

                        {% if album.get_cover_photo %}
                        <div style="height: 200px">
                            <a href="{% url 'gallery:photo' pk=album.id %}">
                                <img class="float-center" src="{{ album.get_cover_photo.image.thumbnail.url }}">
                            </a>
                        </div>
                        {% else %}
                            <img class="float-center" src="https://placehold.it/200x200?text=No photo">
                        {% endif %}
                        <h5 class="card-section text-center">
                            <a class="" href="{% url 'gallery:photo' pk=album.id %}">
                                {{ album.name|truncatechars:50 }}</a>
                        </h5>
                    </div>
                </div>
            {% empty %}
                <div class="float-center">Не найдено</div>
            {% endfor %}
        </div>


{#    </div>#}


    <button class="close-button" data-close aria-label="Close modal" type="button">
        <span aria-hidden="true">&times;</span>
    </button>
</div>

templates/core/include/nav_company.html
{#{% load i18n %}#}
{##}
{# MENU #}
{#<div data-sticky-container>#}
{#<div class="small-12 sticky" data-sticky data-options="marginTop: 0;" style="width:100%">#}
{#<div class="title-bar show-for-small-only" data-responsive-toggle="top-menu">#}
{#    <button class="menu-icon" type="button" data-toggle></button>#}
{#    <div class="title-bar-title" data-toggle>Menu</div>#}
{#</div>#}
{##}
{##}
{##}
{#<div class="top-bar row" id="top-menu">#}
{#    <div class="top-bar-left">#}
{#        <ul class="dropdown vertical medium-horizontal menu">#}
{#            <li class="menu-text">TOASTERS</li>#}
            {#                <li class="has-submenu">#}
            {#                    <a href="#">One</a>#}
            {#                    <ul class="submenu menu vertical" data-submenu>#}
            {#                        <li><a href="#">One</a></li>#}
            {#                        <li><a href="#">Two</a></li>#}
            {#                        <li><a href="#">Three</a></li>#}
            {#                    </ul>#}
            {#                </li>#}
{##}
{#            <li><a href="{% url 'company:companies' %}">Companies</a></li>#}
{#            <li><a href="{% url 'gallery:albums' %}">Gallery</a></li>#}
            {#                <li><a href="{% url 'toast:toasters' %}">Toasters</a></li>#}
            {#                <li><a href="{% url 'toast:tags' %}">Tags</a></li>#}
{#        </ul>#}
{#    </div>#}
{##}
{#    <div class="top-bar-left">#}
{#        <ul class="medium-horizontal menu">#}
{#            <li><a href="{% url 'company:companies' %}">Companies</a></li>#}
{#            <li><a href="{% url 'gallery:albums' %}">Gallery</a></li>#}
{#            <li><a href="#">Blog</a></li>#}
{#            <li><a href="#">About</a></li>#}
{#        </ul>#}
{#    </div>#}
{##}
{#    <div class="top-bar-right">#}
{#        <ul class="dropdown vertical medium-horizontal menu">#}
{##}
{#            <li><input type="search" placeholder={% trans "Search" %}></li>#}
{#            <li><a class="button small">#}
{#                <i class="fas fa-search fa-lg"></i>&nbsp{% trans "Search" %}</a></li>#}
{##}
{#            <li><a id="heart-menu" class="hollow alert button small" data-url="{% url 'api_company:company_list' %}">#}
{#                {% if cnt_fav > 0 %}#}
{#                    <i class="far fa-heart fa-lg fas fav"></i>#}
{#                {% else %}#}
{#                    <i class="far fa-heart fa-lg"></i>#}
{#                {% endif %}#}
{#                <span id="count_fav">#}
{#                    {% if cnt_fav %}{{ cnt_fav }}{% endif %}#}
{#                </span>#}
{#                {% trans "Favorites" %}</a></li>#}
{##}
{#        <p><button class="button" data-open="exampleModal1">Click me for a modal</button></p>#}
{##}
{##}
{#            {% if user.is_authenticated %}#}
{#                {% if user.full_name != '' and user.full_name != None %}#}
{#                    <li><a class="has-tip bottom" href="{% url 'accounts:home' %}" data-tooltip aria-haspopup="true"#}
{#                           data-disable-hover="false" tabindex="4" title="{% trans 'Account' %}">#}
{#                             <i class="far fa-user fa-lg"></i>&nbsp;{{ user.full_name|truncatechars:20 }}</a></li>#}
{#                {% else %}#}
{#                    <li><a class="has-tip bottom" href="{% url 'accounts:home' %}" data-tooltip aria-haspopup="true"#}
{#                           data-disable-hover="false" tabindex="4" title="{% trans 'Account' %}">#}
{#                                 <i class="far fa-user fa-lg"></i>&nbsp;{{ user|truncatechars:20 }}</a></li>#}
{#                {% endif %}#}
{#                <li><a class="icon-button has-tip bottom" href="{% url 'accounts:logout' %}" data-tooltip#}
{#                       aria-haspopup="true" data-disable-hover="false" tabindex="4" title="{% trans 'Log out' %}">#}
{#                            <i class="fas fa-sign-out-alt fa-lg" style="color: blueviolet"></i></a></li>#}
{#            {% else %}#}
{#                <li><a class="icon-button has-tip bottom right" href="{% url 'accounts:register' %}" data-tooltip#}
{#                       aria-haspopup="true" data-disable-hover="false" tabindex="1"#}
{#                       title="{% trans 'Registration for specialists' %}" data-alignment="right">#}
{#                            <i class="fas fa-user-plus fa-lg" style="color: #22bb5b"></i></a></li>#}
{#                <li class=""><a class="icon-button has-tip bottom" href="{% url 'accounts:login' %}" data-tooltip#}
{#                                aria-haspopup="true" data-disable-hover="false" tabindex="4"#}
{#                                title="{% trans "Log in" %}">#}
{#                            <i class="fas fa-sign-in-alt fa-lg" style="color: blueviolet"></i></a></li>#}
{#            {% endif %}#}
{#        </ul>#}
{#    </div>#}
{#</div>#}
{#</div></div>#}
{#<div class="row">#}
{#    <nav aria-label="You are here:" role="navigation">#}
{#        <ul class="row breadcrumbs">#}
{#            <li><a href="#">Home</a></li>#}
{#            <li><a href="#">Features</a></li>#}
{#            <li class="disabled">Gene Splicing</li>#}
{#            <li>#}
{#                <span class="show-for-sr">Current: </span> Cloning#}
{#            </li>#}
{#        </ul>#}
{#    </nav>#}
{#</div>#}
{##}
{#<br>#}


{#<section class="page-section sub-nav light">#}
{#    <div class="small-12 columns text-center sub-nav-links">#}
{#        <ul class="sub-nav-scroll filter-dropdown-links page-section-sub-nav">#}
{#            <li class="page-section-sub-nav-link">#}
{#                <a class="nav-text-link" data-toggle="services-dropdown"><span class="dropdown-arrow">#}
{#All Services#}
{#</span></a>#}
{#                <div class="dropdown-pane" id="services-dropdown" data-dropdown data-close-on-click="true">#}
{#                    <ul class="subnav-dropdown-links">#}
{#                        <li class="filter-link-container">#}
{#                            <a href="/work" class="filter-text-link">All Services</a>#}
{#                        </li>#}
{#                        <li class="filter-link-container"><a class="filter-text-link"#}
{#                                                             href="/work/services/web-applications">Web Applications</a>#}
{#                        </li>#}
{#                        <li class="filter-link-container"><a class="filter-text-link"#}
{#                                                             href="/work/services/ecommerce-sites">eCommerce Sites</a>#}
{#                        </li>#}
{#                        <li class="filter-link-container"><a class="filter-text-link" href="/work/services/web-portals">Web#}
{#                            Portals</a></li>#}
{#                        <li class="filter-link-container"><a class="filter-text-link" href="/work/services/mobile-apps">Mobile#}
{#                            Apps</a></li>#}
{#                        <li class="filter-link-container"><a class="filter-text-link"#}
{#                                                             href="/work/services/user-advocacy">User Advocacy</a></li>#}
{#                        <li class="filter-link-container"><a class="filter-text-link"#}
{#                                                             href="/work/services/emerging-technologies">Emerging#}
{#                            Technologies</a></li>#}
{#                        <li class="filter-link-container"><a class="filter-text-link"#}
{#                                                             href="/work/services/email-design-development-and-strategy">Email#}
{#                            Design Systems</a></li>#}
{#                        <li class="filter-link-container"><a class="filter-text-link"#}
{#                                                             href="/work/services/major-and-data-driven-websites">Data#}
{#                            Driven Websites</a></li>#}
{#                    </ul>#}
{#                </div>#}
{#            </li>#}
{#            <li class="page-section-sub-nav-link">#}
{#                <a href="/work/customers" class="nav-text-link">Customers</a>#}
{#            </li>#}
{#        </ul>#}
{#    </div>#}
{#</section>#}


<div data-sticky-container>
<div class="small-12 sticky" data-sticky  data-stick-to="bottom" data-top-anchor="2"  style="width:100%">

<section class="sticky-shrinknav-header">
{#  <h1 class="sticky-shrinknav-header-title">sticky-shrinknav</h1>#}
  <ul class="menu align-center">
    <li><a href="#">Home</a></li>
    <li><a href="#">About</a></li>
    <li><a href="#">Gallery</a></li>
    <li><a href="#">Contact</a></li>
  </ul>
</section>

</div></div>

templates/core/include/nav_main.html
{% load i18n %}

{# MENU #}
<div data-sticky-container>
<div class="small-12 sticky" data-sticky data-options="marginTop: 0;" style="width:100%">
<div class="title-bar show-for-small-only" data-responsive-toggle="top-menu">
    <button class="menu-icon" type="button" data-toggle></button>
    <div class="title-bar-title" data-toggle>Menu</div>
</div>

<div class="top-bar row" id="top-menu">
    <div class="top-bar-left">
        <ul class="vertical medium-horizontal menu">
            <li class="menu-text"><a href="{% url 'company:companies' %}">TOASTERS</a></li>
        </ul>
    </div>

    <div class="top-bar-left">
        <ul class="medium-horizontal menu">

            <li class="{% if request.resolver_match.view_name == 'company:companies' %}active-menu{% endif %}">
                <a href="{% url 'company:companies' %}">{% trans 'Companies' %}</a></li>
            <li class="{% if request.resolver_match.view_name == 'gallery:albums' %}active-menu{% endif %}">
                <a href="{% url 'gallery:albums' %}">{% trans 'Gallery' %}</a></li>
{#            <li><a href="{% url 'gallery:albums' %}">{% trans 'Gallery' %}</a></li>#}
            <li><a href="#">{% trans 'Blog' %}</a></li>
            <li><a href="#">{% trans 'About' %}</a></li>
        </ul>
    </div>

    <div class="top-bar-right">
        <ul class="dropdown vertical medium-horizontal menu">

{#            <li><input type="search" placeholder={% trans "Search" %}></li>#}
{#            <li><a class="button small">#}
{#                <i class="fas fa-search fa-lg"></i>&nbsp{% trans "Search" %}</a></li>#}

            <li><a id="heart-menu" class="hollow alert button small" data-url="{% url 'api_company:company_list' %}">
                {% if cnt_fav > 0 %}
                    <i class="far fa-heart fa-lg fas fav"></i>
                {% else %}
                    <i class="far fa-heart fa-lg"></i>
                {% endif %}
                <span id="count_fav">
                    {% if cnt_fav %}{{ cnt_fav }}{% endif %}
                </span>
                {% trans "Favorites" %}</a></li>

{#        <p><button class="button" data-open="exampleModal1">Click me for a modal</button></p>#}


            {% if user.is_authenticated %}
                {% if user.full_name != '' and user.full_name != None %}
                    <li><a class="has-tip bottom" href="{% url 'dashboard' %}" data-tooltip aria-haspopup="true"
                           data-disable-hover="false" tabindex="4" title="{% trans 'Account' %}">
                             <i class="far fa-user fa-lg"></i>&nbsp;{{ user.full_name|truncatechars:20 }}</a></li>
                {% else %}
                    <li><a class="has-tip bottom" href="{% url 'dashboard' %}" data-tooltip aria-haspopup="true"
                           data-disable-hover="false" tabindex="4" title="{% trans 'Account' %}">
                                 <i class="far fa-user fa-lg"></i>&nbsp;{{ user|truncatechars:20 }}</a></li>
                {% endif %}
                <li><a class="icon-button has-tip bottom" href="{% url 'accounts:logout' %}" data-tooltip
                       aria-haspopup="true" data-disable-hover="false" tabindex="4" title="{% trans 'Log out' %}">
                            <i class="fas fa-sign-out-alt fa-lg" style="color: blueviolet"></i></a></li>
            {% else %}
                <li><a class="icon-button has-tip bottom right" href="{% url 'accounts:register' %}" data-tooltip
                       aria-haspopup="true" data-disable-hover="false" tabindex="1"
                       title="{% trans 'Registration for specialists' %}" data-alignment="right">
                            <i class="fas fa-user-plus fa-lg" style="color: #22bb5b"></i></a></li>
                <li class=""><a class="icon-button has-tip bottom" href="{% url 'accounts:login' %}" data-tooltip
                                aria-haspopup="true" data-disable-hover="false" tabindex="4"
                                title="{% trans "Log in" %}">
                            <i class="fas fa-sign-in-alt fa-lg" style="color: blueviolet"></i></a></li>
            {% endif %}
        </ul>
    </div>
</div>
</div></div>
{#<div class="row">#}
{#    <nav aria-label="You are here:" role="navigation">#}
{#        <ul class="row breadcrumbs">#}
{#            <li><a href="#">Home</a></li>#}
{#            <li><a href="#">Features</a></li>#}
{#            <li class="disabled">Gene Splicing</li>#}
{#            <li>#}
{#                <span class="show-for-sr">Current: </span> Cloning#}
{#            </li>#}
{#        </ul>#}
{#    </nav>#}
{#</div>#}
{##}
{#<br>#}

templates/core/include/nav_main_one.html
{% load i18n %}
{% url 'company:companies' location='' type='' price='' as url_companies %}
{% url 'company:companies' location='empty/' type='vedushie-tamada/' as url_tamada %}
{% url 'company:companies' location='empty/' type='fotografy/' as url_foto %}
<div data-sticky-container>
    <div class="small-12 sticky" data-sticky data-options="marginTop: 0;" style="width:100%">
        <nav class="top-bar topbar-responsive">
            <div class="top-bar-title">
                <span data-responsive-toggle="topbar-responsive" data-hide-for="medium">
                  <button class="menu-icon" type="button" data-toggle></button>
                </span>
                <a class="topbar-responsive-logo menu-text" href="{% url 'company:companies' %}">TOASTERS</a>
            </div>
            <div id="topbar-responsive" class="topbar-responsive-links">
                <div class="top-bar-right">
                    <ul class="menu dropdown simple vertical medium-horizontal" data-dropdown-menu>
{#                        {{ request.get_full_path }}#}
{#                        {{ url_foto }}#}
                        <li class="{% if 'vedushie-tamada/' in request.path %}active-menu{% endif %}">
                            <a href="{{ url_tamada }}">{% trans 'Toasters' %}</a></li>
                        <li class="{% if 'fotografy/' in request.path %}active-menu{% endif %}">
                            <a href="{{ url_foto }}">{% trans 'Photographers' %}</a></li>
{#                        <li class="{% if request.resolver_match.view_name == 'company:companies' %}active-menu{% endif %}">#}
{#                            <a href="{% url 'company:companies' %}?type=videooperator">{% trans 'Videographer' %}</a></li>#}
                        <li class="{% if request.path == url_companies %}active-menu{% endif %}">
                            <a href="{% url 'company:companies' %}">{% trans 'Companies' %}</a></li>
                        <li class="{% if request.resolver_match.view_name == 'gallery:albums' %}active-menu{% endif %}">
                            <a href="{% url 'gallery:albums' %}">{% trans 'Gallery' %}</a></li>
                        <li class="{% if request.resolver_match.view_name == 'gallery:photos' %}active-menu{% endif %}">
                            <a href="{% url 'gallery:photos' %}">{% trans 'Photos' %}</a></li>
                        <li><a href="#">{% trans 'Blog' %}</a></li>
                        <li><a href="#">{% trans 'About' %}</a></li>

                        {% if user.is_authenticated %}
                            {% if user.full_name != '' and user.full_name != None %}
                                <li><a class="bottom
                                    {% if request.resolver_match.view_name == 'accounts:dashboard' %}active-menu{% endif %}"
                                       href="{% url 'accounts:dashboard' %}" title="{% trans 'Account' %}">
                                    <i class="far fa-user fa-lg"></i>&nbsp;{{ user.full_name|truncatechars:20 }}</a>
                                </li>
                            {% else %}
                                <li><a class="bottom
                                    {% if request.resolver_match.view_name == 'accounts:dashboard' %}active-menu{% endif %}"
                                       href="{% url 'accounts:dashboard' %}" title="{% trans 'Account' %}">
                                    <i class="far fa-user fa-lg"></i>&nbsp;{{ user|truncatechars:20 }}</a></li>
                            {% endif %}
                            <li><a class="button hollow button-log" href="{% url 'accounts:logout' %}"
                                   title="{% trans 'Log out' %}">{% trans 'Log out' %}</a></li>

                        {% else %}
                            <li><a class="button hollow button-register
                                    {% if request.resolver_match.view_name == 'accounts:register' %}active-menu{% endif %}"
                                   href="{% url 'accounts:register' %}"
                                   title="{% trans "Log in" %}">{% trans 'Register' %}
                            </a></li>
                            <li><a class="button hollow button-log
                                    {% if request.resolver_match.view_name == 'accounts:login' %}active-menu{% endif %}"
                                   href="{% url 'accounts:login' %}" title="{% trans "Log in" %}">{% trans "Log in" %}
                            </a></li>
                        {% endif %}
                    </ul>
                </div>
            </div>
        </nav>
    </div>
</div>