accounts/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views

from .views import (
    AccountDashboardView,
    AccountActivateView,
    LoginView,
    RegisterView,
    DoneRegisterView,
    UserDetailUpdateView,
    UserPasswordChangeView,
)

urlpatterns = [
    url(r'^dashboard/$', AccountDashboardView.as_view(), name='dashboard'),
    url(r'^login/$', LoginView.as_view(), name='login'),
    url(r'^logout/$', auth_views.logout, name='logout'),
    url(r'^register/$', RegisterView.as_view(), name='register'),
    url(r'^register/done/$', DoneRegisterView.as_view(), name='register_done'),
    url(r'^activate/(?P<uidb64>[0-9A-Za-z]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        AccountActivateView.as_view(), name='activate'),
    url(r'^password/$', UserPasswordChangeView.as_view(), name='change_password'),
    url(r'^details/$', UserDetailUpdateView.as_view(), name='user-update'),

    # Password Reset View
    url(r'^password_reset/$',
        auth_views.password_reset, {
            'template_name': 'password_reset/password_reset_form.html',
            'email_template_name': 'password_reset/password_reset_email.html',
            'subject_template_name': 'password_reset/password_reset_subject.txt',
            'post_reset_redirect': 'accounts:password_reset_done',
        },
        name='password_reset'),

    url(r'^password_reset/done/$', auth_views.password_reset_done, {
        'template_name': 'password_reset/password_reset_done.html',
        },
        name='password_reset_done'),

    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        auth_views.password_reset_confirm, {
            'template_name': 'password_reset/password_reset_confirm.html',
            'post_reset_redirect': 'accounts:password_reset_complete',
        },
        name='password_reset_confirm'),

    url(r'^reset/done/$', auth_views.password_reset_complete, {
        'template_name': 'password_reset/password_reset_complete.html',
        },
        name='password_reset_complete')
]

core/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf.urls.static import static

import django.views.static
from django.conf import settings


urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^ckeditor/', include('ckeditor_uploader.urls')),
    # url(r'^toasters/', include('toast.urls', namespace='toast')),
    url(r'^company/', include('company.urls', namespace='company')),
    url(r'^tags/', include('tags.urls', namespace='tags')),
    url(r'gallery/', include('gallery.urls', namespace='gallery')),

    url(r'^media/(?P<path>.*)$', django.views.static.serve, {'document_root': settings.MEDIA_ROOT}),

    url(r'^accounts/', include('accounts.urls', namespace='accounts')),

    url(r'^api/v1/company/', include('company.api.urls', namespace='api_company')),
    url(r'^api/v1/gallery/', include('gallery.api.urls', namespace='api_gallery'))
]

# if settings.DEBUG:
#     if settings.MEDIA_URL:
#         urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_URL)
#         urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

gallery/api/urls.py
from django.conf.urls import url

from .views import PhotoListAPIView

urlpatterns = [
    # url(r'^(?P<pk>\d+)/$', SessionAPIView.as_view(), name='favorite'),
    url(r'^photo-list/$', PhotoListAPIView.as_view(), name='photo_list'),
]

gallery/urls.py
from django.conf.urls import url

from .views import (
    AlbumListView,
    PhotoListView,
    PhotoAddView,
    AlbumAddView,
    AlbumUpdateView,
    AlbumDeleteView,

    PhotosListView,
)


urlpatterns = [
    url(r'^albums/$', AlbumListView.as_view(), name='albums'),
    url(r'^album/(?P<pk>\d+)/$', PhotoListView.as_view(), name='photo'),
    url(r'^photo-add/$', PhotoAddView.as_view(), name='photo_add'),
    url(r'^album/add/$', AlbumAddView.as_view(), name='album_add'),
    url(r'^album/(?P<pk>\d+)/update/$', AlbumUpdateView.as_view(), name='album_update'),
    url(r'^album/(?P<pk>\d+)/delete/$', AlbumDeleteView.as_view(), name='album_delete'),

    url(r'^photos/$', PhotosListView.as_view(), name='photos'),

    # url(r'^add/$', CompanyAddView.as_view(), name='company_add'),
    # url(r'^update/(?P<pk>\d+)/$', CompanyUpdateView.as_view(), name='company_update'),
    # url(r'^delete/(?P<pk>\d+)/$', CompanyDeleteView.as_view(), name='company_delete'),
    # url(r'^(?P<pk>\d+)/$', CompanyDetailView.as_view(), name='company_detail'),
    # url(r'^profile_update/$', ProfileCreateView.as_view(), name='profile-update'),
]

gallery/api/views.py
from rest_framework import generics
from rest_framework.generics import ListAPIView, RetrieveUpdateDestroyAPIView

from rest_framework.response import Response
from .serializers import PhotoSerializer
from gallery.models import Photo


class PhotoListAPIView(ListAPIView):
    queryset = Photo.pub_objects.all()
    serializer_class = PhotoSerializer

    # def get_favorites(self):
    #     if self.request.session.__contains__('favorite'):
    #         return self.request.session.get('favorite')
    #     return dict()

    # def get_queryset(self):
    #     # qs = []
    #     # for comp in Company.pub_objects.all():
    #     #     if comp.id in self.get_favorites():
    #     #         qs.append(comp)
    #     return [comp for comp in Photo.pub_objects.all()
    #             if int(comp.id) in self.get_favorites()]

    # def get_context_data(self, **kwargs):
    #     super(CompanyListAPIView, self).get_context_data(**kwargs)

gallery/views.py
from django.shortcuts import render, render_to_response
from django.db import transaction
from django.http import HttpResponseRedirect

from django.views.generic import ListView, DetailView, UpdateView, View, DeleteView, CreateView
from django.utils.translation import ugettext as _

from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.urlresolvers import reverse_lazy

from django.contrib import messages
from django.contrib.messages.views import SuccessMessageMixin
from .messages import ErrorMessageMixin
from .models import Album, Photo

from django.forms import inlineformset_factory
from .forms import PhotoAddForm, AlbumForm, PhotoFormSet

from company.models import Company


class AlbumListView(ListView):
    model = Album
    template_name = 'gallery/album_list.html'
    context_object_name = 'albums'
    title = _('Albums')

    def get_context_data(self, **kwargs):
        context = super(AlbumListView, self).get_context_data(**kwargs)
        context.update({'title': self.title})
        return context


class PhotoListView(ListView):
    model = Photo
    template_name = 'gallery/photo_list.html'
    context_object_name = 'photos'

    def get_context_data(self, **kwargs):
        context = super(PhotoListView, self).get_context_data(**kwargs)
        current_album = Album.objects.get(id=self.kwargs['pk'])
        current_company = current_album.company
        more_albums = [album for album in Album.objects.filter(company_id=current_company.id)
                       if album.is_album_empty() is False]
        context.update({
            'current_album': current_album,
            'current_company': current_company,
            'more_albums': more_albums,
        })
        return context

    def get_queryset(self):
        return Photo.objects.filter(album_id=self.kwargs['pk']).order_by('-created')


class PhotosListView(ListView):
    model = Photo
    template_name = 'gallery/photos.html'
    title = _("Gallery")

    def get_context_data(self, **kwargs):
        context = super(PhotosListView, self).get_context_data(**kwargs)
        context.update({'title': self.title})
        return context


class PhotoAddView(SuccessMessageMixin,
                   ErrorMessageMixin,
                   LoginRequiredMixin,
                   CreateView):
    form_class = PhotoAddForm
    model = Photo
    success_url = reverse_lazy('accounts:dashboard')
    success_message = _('Photo %(name)s was created successfully!')
    error_message = _('Please correct the errors below.')
    title = _("Add Photo")

    def get_context_data(self, **kwargs):
        context = super(PhotoAddView, self).get_context_data(**kwargs)
        context.update({'title': self.title})
        return context

    def get_form_kwargs(self):
        kwargs = super(PhotoAddView, self).get_form_kwargs()
        kwargs.update({'user': self.request.user})
        return kwargs

    def form_invalid(self, form):
        context = {'form': form, 'title': self.title}
        messages.error(self.request, self.error_message)
        return render(self.request, 'gallery/photo_form.html', context)


# class AlbumAddView(SuccessMessageMixin,
#                    ErrorMessageMixin,
#                    LoginRequiredMixin,
#                    CreateView):
#     error_message = _('Please correct the errors below.')
#     form_class = AlbumForm
#     model = Album
#     success_url = reverse_lazy('accounts:dashboard')
#     success_message = _('Album "%(name)s" was created successfully!')
#     template_name = 'gallery/manage_photo.html'
#     title = _("Сreate an album")
#
#     def get(self, request, *args, **kwargs):
#         self.object = None
#         form_class = self.get_form_class()
#         form = self.get_form(form_class)
#         photo_form = PhotoFormSet()
#         return self.render_to_response(
#             self.get_context_data(form=form, photo_form=photo_form)
#         )
#
#     def post(self, request, *args, **kwargs):
#         self.object = None
#         form_class = self.get_form_class()
#         form = self.get_form(form_class)
#         photo_form = PhotoFormSet(self.request.POST, self.request.FILES, instance=self.object)
#
#         if form.is_valid() and photo_form.is_valid():
#             return self.form_valid(form, photo_form)
#         else:
#             return self.form_invalid(form, photo_form)
#
#     def get_form_kwargs(self):
#         kwargs = super(AlbumAddView, self).get_form_kwargs()
#         kwargs.update({'user': self.request.user})
#         print("KWARGS: ", kwargs)
#         return kwargs
#
#     def form_valid(self, form, photo_form):
#         with transaction.atomic():
#             self.object = form.save()
#             if photo_form.is_valid():
#                 photo_form.instance = self.object
#                 print("photo_form", photo_form)
#                 print("photo_form.instance", photo_form.instance.author_id)
#                 photo_form.save()
#         return super(AlbumAddView, self).form_valid(form)
#
#     def form_invalid(self, form, photo_form):
#         messages.error(self.request, self.error_message)
#         return self.render_to_response(
#             self.get_context_data(form=form, photo_form=photo_form)
#         )
#
#     def get_context_data(self, **kwargs):
#         ctx = super(AlbumAddView, self).get_context_data(**kwargs)
#         ctx.update({'title': self.title})
#         if self.request.POST:
#             form_class = self.get_form_class()
#             ctx['form'] = form_class(self.request.POST, instance=self.object)
#             ctx['photo_form'] = PhotoFormSet(self.request.POST, self.request.FILES, instance=self.object)
#         else:
#             form_class = self.get_form_class()
#             ctx['form'] = self.get_form(form_class)
#             ctx['photo_form'] = PhotoFormSet(instance=self.object)
#         return ctx

class AlbumAddView(SuccessMessageMixin,
                   ErrorMessageMixin,
                   LoginRequiredMixin,
                   CreateView):
    error_message = _('Please correct the errors below.')
    form_class = AlbumForm
    model = Album
    success_url = reverse_lazy('accounts:dashboard')
    success_message = _('Album "%(name)s" was created successfully!')
    template_name = 'gallery/manage_photo.html'
    title = _("Сreate an album")
    PhotosFormSet = inlineformset_factory(Album, Photo, fields=('name', 'image', 'is_cover_photo'))

    def get(self, request, *args, **kwargs):
        self.object = None
        form_class = self.get_form_class()
        form = self.get_form(form_class)
        photo_formset = self.PhotosFormSet()
        return self.render_to_response(
            self.get_context_data(form=form, photo_form=photo_formset)
        )

    def post(self, request, *args, **kwargs):
        self.object = None
        form_class = self.get_form_class()
        form = self.get_form(form_class)

        photo_formset = self.PhotosFormSet(self.request.POST, self.request.FILES, instance=self.object)

        if form.is_valid() and photo_formset.is_valid():
            return self.form_valid(form, photo_formset)
        else:
            return self.form_invalid(form, photo_formset)

    def get_form_kwargs(self):
        kwargs = super(AlbumAddView, self).get_form_kwargs()
        kwargs.update({'user': self.request.user})
        return kwargs

    def form_valid(self, form, photo_formset):
        kwargs = self.get_form_kwargs()
        with transaction.atomic():
            self.object = form.save()
            if photo_formset.is_valid():
                photo_formset.instance = self.object
                formset = photo_formset.save(commit=False)
                for photo in formset:
                    photo.author = kwargs['user']
                photo_formset.save()
        return super(AlbumAddView, self).form_valid(form)

    def form_invalid(self, form, photo_form):
        messages.error(self.request, self.error_message)
        return self.render_to_response(
            self.get_context_data(form=form, photo_form=photo_form)
        )

    def get_context_data(self, **kwargs):
        ctx = super(AlbumAddView, self).get_context_data(**kwargs)
        ctx.update({'title': self.title})
        if self.request.POST:
            form_class = self.get_form_class()
            ctx['form'] = form_class(self.request.POST, instance=self.object)
            ctx['photo_form'] = PhotoFormSet(self.request.POST, self.request.FILES, instance=self.object)
        else:
            form_class = self.get_form_class()
            ctx['form'] = self.get_form(form_class)
            ctx['photo_form'] = PhotoFormSet(instance=self.object)
        return ctx


class AlbumUpdateView(SuccessMessageMixin,
                      ErrorMessageMixin,
                      LoginRequiredMixin,
                      UpdateView):
    error_message = _('Please correct the errors below.')
    form_class = AlbumForm
    model = Album
    success_url = reverse_lazy('accounts:dashboard')
    success_message = _('Album "%(name)s" was updated successfully!')
    template_name = 'gallery/manage_photo.html'
    title = _("Update Album")

    def get_object(self, queryset=None):
        obj = Album.objects.get(pk=self.kwargs['pk'])
        return obj

    def get(self, request, *args, **kwargs):
        self.object = self.get_object()
        form_class = self.get_form_class()
        form = self.get_form(form_class)
        photo_form = PhotoFormSet(self.request.FILES, instance=self.object)
        return self.render_to_response(
            self.get_context_data(form=form, photo_form=photo_form)
        )

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        form_class = self.get_form_class()
        form = self.get_form(form_class)
        photo_form = PhotoFormSet(self.request.POST, self.request.FILES, instance=self.object)

gallery/templates/gallery/album_confirm_delete.html
{% extends 'core/base.html' %}
{% load i18n %}

{% block title %}
    {{ title }}
{% endblock %}


{% block content  %}
<div class="row grid-x">
    <div class="cell small-9 medium-7 large-5 float-center">
    <div class="card">
         <div class="card-divider">
            {% if title %}<h4 class=''>{{ title }}</h4>{% endif %}
        </div>
        <div class="card-section no-bullet me">
            <p>{% trans "Are you sure you want to delete the selected Album?" %}</p>
        <form method="post">
            {% csrf_token %}
            <button type='submit' class='button alert small'>{% trans "Yes, I'm sure" %}</button>
            <a class="button secondary small " href="{% url 'accounts:dashboard' %}">{% trans "No, take me back" %}</a>
        </form>
        </div>

    </div>
    </div>
</div>
{% endblock %}

gallery/templates/gallery/album_list.html
{% extends 'core/base.html' %}
{% load i18n %}

{% block title %}
    {{ title }}
{% endblock %}

{% block header %}{% endblock %}

{% block content %}
    <div class="grid-x grid-margin-y">

        {# LIST CARDS #}
        <div class="cell row small-12 medium-8 large-9">
            <div class="grid-margin-y">

                {# HEADER #}
{#                <h3 class="subheader text-center">#}
{#                    {% if header.location %}{% trans 'City' %}: {{ header.location }}{% endif %}#}
{#                    {% if header.type %}{% trans 'Type' %}: {{ header.type }}{% endif %}#}
{#                    {% if header.price %}{% trans 'Price' %}: {{ header.price }}{% endif %}#}
{#                </h3>#}

                {# CARDS #}
                <div class="grid-x grid-margin-x grid-margin-y align-left">
                    {% for album in albums %}
                        <div class="cell small-12 medium-4 large-3">
                            <div class="thumbnail card " style="height: 100%; width: 100%;">

                                {% if album.get_cover_photo %}
                                <div style="height: 200px">
                                    <a href="{% url 'gallery:photo' pk=album.id %}">
                                        <img class="float-center" src="{{ album.get_cover_photo.image.thumbnail.url }}">
                                    </a>
                                </div>
                                {% else %}
                                    <img class="float-center" src="https://placehold.it/200x200?text=No photo">
                                {% endif %}
                                <h5 class="card-section text-center">
                                    <a class=""
                                       href="{% url 'gallery:photo' pk=album.id %}">
                                    {{ album.name|truncatechars:50 }}
                                    </a>
                                    <br>{{ album.summary|truncatechars:50 }}
                                </h5>
                            </div>
                        </div>
                    {% empty %}
                        <div class="float-center">Не найдено</div>
                    {% endfor %}
                </div>

                {# PAGINATION #}
                {% if page_obj.paginator.num_pages > 1 %}
                <nav class="cell" aria-label="Pagination">
                    <ul class="pagination text-center">
                        {% if page_obj.has_previous %}
                            <li class="pagination-previous">
                                <a href="?type_company={{ request.GET.type_company }}&location_select={{ request.GET.location_select }}&price={{ request.GET.price }}&page={{ page_obj.previous_page_number }}"
                                   aria-label="Previous page">{% trans "Previous" %} <span class="show-for-sr">page</span>
                                </a></li>
                            {% for page in page_obj.paginator.page_range|slice:page_dict.prev %}
                                <li><a {% if page_obj.number == page %} class="current" {% endif %}
                                                                        href="?type_company={{ request.GET.type_company }}&location_select={{ request.GET.location_select }}&price={{ request.GET.price }}&page={{ page }}"
                                >{{ page }}</a></li>
                            {% endfor %}
                        {% else %}
                            <li class="pagination-previous disabled">{% trans "Previous" %} <span class="show-for-sr"></span></li>
                        {% endif %}

                        <li><a class="current"
                               href="?type_company={{ request.GET.type_company }}&location_select={{ request.GET.location_select }}&price={{ request.GET.price }}&page={{ page_obj.number }}"
                        >{{ page_obj.number }}</a></li>

                        {% if page_obj.has_next %}
                            {% for page in page_obj.paginator.page_range|slice:page_dict.next %}
                                <li><a {% if page_obj.number == page %} class="current" {% endif %}
                                                                        href="?type_company={{ request.GET.type_company }}&location_select={{ request.GET.location_select }}&price={{ request.GET.price }}&page={{ page }}"
                                >{{ page }}</a></li>
                            {% endfor %}

                            <li class="pagination-next">
                                <a href="?type_company={{ request.GET.type_company }}&location_select={{ request.GET.location_select }}&price={{ request.GET.price }}&page={{ page_obj.next_page_number }}"
                                   aria-label="Next page">{% trans "Next" %} <span class="show-for-sr"></span></a></li>
                        {% else %}
                            <li class="pagination-next disabled">{% trans "Next" %} <span class="show-for-sr"></span></li>
                        {% endif %}
                    </ul>
                </nav>
                {% endif %}
            </div>
        </div>
    </div>




{% endblock %}

gallery/templates/gallery/manage_photo.html
{% extends 'core/base.html' %}
{% load staticfiles %}
{% load i18n %}

{% block title %}
    {{ title }}
{% endblock %}

{% block content  %}
{% url 'gallery:album_add' as url_album_add %}
{% url 'gallery:album_update' pk=album.pk as url_album_update %}
    <div class="row">
            {% if title %}<h4 class='header'>{{ title }}</h4><hr>{% endif %}
            <form data-abide novalidate method="POST" enctype="multipart/form-data">{% csrf_token %}
                <div class="grid-x grid-y">
                    <div class="float-center">
                        <div class="small-12 medium-6">
                            {{ form.name.errors }}
                            {{ form.name.label_tag }} {{ form.name }}
                        </div>
                        <div class="small-12 medium-6">
                            {{ form.summary.errors }}
                            {{ form.summary.label_tag }} {{ form.summary }}
                        </div>
                    </div>
                </div>
{#                {% for photo in photos %}#}
{#                    <img src="{{ photo.image.small.url }}" alt="">#}
{#                {% endfor %}#}

                <table class="table">
                    {{ photo_form.management_form }}

                    {% for form in photo_form.forms %}
                        {% if forloop.first %}
                            <thead>
                            <tr>
                                {% for field in form.visible_fields %}
                                    <th>{{ field.label|capfirst }}</th>
                                {% endfor %}
                            </tr>
                            </thead>
                        {% endif %}

                        <tr class="formset_row">
                            {% for field in form.visible_fields %}
                                <td>
                                    {# Include the hidden fields in the form #}
                                    {% if forloop.first %}
                                        {% for hidden in form.hidden_fields %}
                                            {{ hidden }}
                                        {% endfor %}
                                    {% endif %}
                                    {{ field.errors.as_ul }}
                                    {{ field }}
{#                                    {% if field.name == 'image' %}#}
{#                                        <img src="{{ field.value.small.url }}" alt="">#}
{#                                        {{ field.value }}#}
{#                                    {% endif %}#}
                                </td>
                            {% endfor %}
                        </tr>
                {% endfor %}
                </table>

                {% if request.path == url_album_add %}
                    <div class="button-group small medium-offset-3">
                        <a class="button secondary" href="{% url 'accounts:dashboard' %}">{% trans "Cancel" %}</a>
                        <button type='submit' class='button success'>{% trans "Add album" %}</button>
                    </div>
                {% elif request.path == url_album_update %}
                    <div class="button-group small medium-offset-3">
                        <a class="button alert small" href="{% url 'gallery:album_delete' pk=album.pk %}">{% trans "Delete" %}</a>
                        <a class="button secondary" href="{% url 'accounts:dashboard' %}">{% trans "Cancel" %}</a>
                        <button type='submit' class='button success'>{% trans "Update album" %}</button>
                    </div>
                {% endif %}
            </form>
    </div>
{% endblock %}

{% block javascript %}
<script src="{% static 'js/django-dynamic-formset/src/jquery.formset.js' %}"></script>
<script type="text/javascript">
    $('.formset_row').formset({
        addText: '<i class="fas fa-plus fa-lg" style="color: green;"></i>&nbsp;{% trans "add photo" %}',
        deleteText: '<i class="far fa-trash-alt fa-lg float-center" style="color: red;"></i>',
        prefix: 'photo_set'
    });
</script>
{% endblock %}

gallery/templates/gallery/photo_list.html
{% extends 'core/base.html' %}
{% load staticfiles %}
{% load i18n %}

{% block title %}
    {{ current_album }} | {{ current_company }}
{% endblock %}
{% block link %}
    <link href="{% static 'css/user_card.css' %}" rel="stylesheet"/>
{% endblock %}

{#{% block header %}#}
{#    <h2 class="subheader">Тамада и ведущий на свадьбу{% if header %}: {{ header }}{% endif %}</h2>#}
{#{% endblock %}#}

{% block content %}
    <div class="grid-x grid-margin-x">

        {# LEFT #}
        <div class="cell row small-12 medium-8 large-9">
            <div class="grid-margin-y">

                {#  Show photos #}
                <div class="cell grid-x align-left">
                    <h5 class="cell">{{ current_album.name }}
                        <span class="badge success">{{ photos.all.count }}</span>
                        <hr>
                    </h5>
                    {% for photo in photos %}
                        <div class="cell small-12 medium-6 large-3">
                            <div class="portfolio-item thumbnail">
                                <div class="hover-bg">
                                    <div style="height: 200px">
                                        <div class="hover-text">
                                        <h4>Lorem Ipsum</h4>
                                    </div>
                                    <img class="float-center " src="{{ photo.image.thumbnail.url }}">
                                </div>
                                </div>

                            </div>
                        </div>
                    {% empty %}
                        {% trans "Empty" %}
                    {% endfor %}
                </div>

                {# Current company #}
                <h5 class="cell">

                <a href="">
                <img id="avatar" class="thumbnail" src="{{ current_company.avatar.small.url }}">
                </a>

                    {% trans "Author" %}: {{ current_company }}<hr>
                </h5>
                <!-- Show more albums -->
                <div class="cell grid-x grid-margin-y align-left" >
                <h5 class="cell">
                    <small>{% trans "All albums" %}</small>
                    <span class="badge success"> {{ more_albums|length }}</span><hr>
                </h5>
                    {% for album in more_albums %}
                        <div class="cell small-12 medium-6 large-3">
                            <div class="thumbnail">
                                <div style="height: 200px">
                                    <a href="{% url 'gallery:photo' pk=album.id %}">
                                    <img class="float-center"
                                         src="{{ album.get_cover_photo.image.thumbnail.url }}">
                                    </a>
                                </div>

                                <h5 class="card-section text-center">
                                    <a href="{% url 'gallery:photo' pk=album.id %}">
                                    {{ album.name }}</a>
                                </h5>
                            </div>
                        </div>
                    {% endfor %}
                </div>



            </div>
        </div>

        <!-- RIGHT / Advertising -->



{#    <!-- User card example #1 -->#}
{#    <div class="cell small-12 medium-3 large-3 card-user-container">#}
{##}
{#  <!--card's image-->#}
{#  <div class="card-user-avatar">#}
{#    <img src="{{ current_company.avatar.thumbnail.url }}" alt="" class="user-image">#}
{#  </div>#}
{##}
{#  <!--user info name, bio and location-->#}
{#  <div class="card-user-bio">#}
{#    <h4>{{ current_company }}</h4>#}
{#    <p>{{ current_company }}/p>#}
{#    <span class="location"><span class="location-icon fa fa-map-marker"></span><span class="location-text">Makkah Al-Mukaramah</span></span>#}
{#  </div>#}
{##}
{#  <!--card's socail icons-->#}
{#  <div class="card-user-social">#}
{#    <ul class="menu">#}
{#      <li class="fa fa-twitter"></li>#}
{#      <li class="fa fa-dribbble"></li>#}
{#      <li class="fa fa-instagram"></li>#}
{#      <li class="fa fa-github"></li>#}
{#    </ul>#}
{#  </div>#}
{##}
{#  <!--card's follow button-->#}
{#  <div class="card-user-button">#}
{#    <a href="#" class="hollow button">FOLLOW</a>#}
{#  </div>#}
{#</div>#}




{#        <div class="cell small-12 medium-3 large-3">#}
{#            <div class="grid-x grid-margin-y">#}
{#                <div class="cell small-12 medium-12 large-12">#}
{#                    <img class="thumbnail float-center" src="https://placehold.it/400x500">#}
{#                </div>#}
{#                <div class="cell small-12 medium-12 large-12">#}
{#                    <img class="thumbnail float-center" src="https://placehold.it/400x500">#}
{#                </div>#}
{#                <div class="cell small-12 medium-12 large-12">#}
{#                    <img class="thumbnail float-center" src="https://placehold.it/400x500">#}
{#                </div>#}
{#                <div class="cell small-12 medium-12 large-12">#}
{#                    <img class="thumbnail float-center" src="https://placehold.it/400x500">#}
{#                </div>#}
{#            </div>#}
{#        </div>#}
    </div>
{% endblock %}