accounts/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views

from .views import (
    AccountDashboardView,
    AccountActivateView,
    LoginView,
    RegisterView,
    DoneRegisterView,
    UserDetailUpdateView,
    UserPasswordChangeView,
)

urlpatterns = [
    url(r'^dashboard/$', AccountDashboardView.as_view(), name='dashboard'),
    url(r'^login/$', LoginView.as_view(), name='login'),
    url(r'^logout/$', auth_views.logout, name='logout'),
    url(r'^register/$', RegisterView.as_view(), name='register'),
    url(r'^register/done/$', DoneRegisterView.as_view(), name='register_done'),
    url(r'^activate/(?P<uidb64>[0-9A-Za-z]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        AccountActivateView.as_view(), name='activate'),
    url(r'^password/$', UserPasswordChangeView.as_view(), name='change_password'),
    url(r'^details/$', UserDetailUpdateView.as_view(), name='user-update'),

    # Password Reset View
    url(r'^password_reset/$',
        auth_views.password_reset, {
            'template_name': 'password_reset/password_reset_form.html',
            'email_template_name': 'password_reset/password_reset_email.html',
            'subject_template_name': 'password_reset/password_reset_subject.txt',
            'post_reset_redirect': 'accounts:password_reset_done',
        },
        name='password_reset'),

    url(r'^password_reset/done/$', auth_views.password_reset_done, {
        'template_name': 'password_reset/password_reset_done.html',
        },
        name='password_reset_done'),

    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        auth_views.password_reset_confirm, {
            'template_name': 'password_reset/password_reset_confirm.html',
            'post_reset_redirect': 'accounts:password_reset_complete',
        },
        name='password_reset_confirm'),

    url(r'^reset/done/$', auth_views.password_reset_complete, {
        'template_name': 'password_reset/password_reset_complete.html',
        },
        name='password_reset_complete')
]

company/urls.py
from django.conf.urls import url

from .views import (
    CompanyListView,
    CompanyAddView,
    CompanyDetailView,
    CompanyUpdateView,
    CompanyDeleteView,
    # CompanyCreate
)

urlpatterns = [
    # url(r'^$', CompanyListView.as_view(), name='companies'),
    url(r'^filter/(?P<location>[a-z\-]+)?/?(?P<type>[a-z\-]+)?/?(?P<price>[a-z0-9\-]+)?/?$', CompanyListView.as_view(), name='companies'),
    # url(r'^toaster/$', CompanyListView.as_view(), name='companies'),
    url(r'^add/$', CompanyAddView.as_view(), name='company_add'),
    # url(r'^add/$', CompanyCreate.as_view(), name='company_add'),
    url(r'^update/(?P<pk>\d+)/$', CompanyUpdateView.as_view(), name='company_update'),
    url(r'^delete/(?P<pk>\d+)/$', CompanyDeleteView.as_view(), name='company_delete'),
    url(r'^(?P<pk>\d+)/$', CompanyDetailView.as_view(), name='company_detail'),
    # url(r'^profile_update/$', ProfileCreateView.as_view(), name='profile-update'),
]

core/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf.urls.static import static

import django.views.static
from django.conf import settings


urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^ckeditor/', include('ckeditor_uploader.urls')),
    # url(r'^toasters/', include('toast.urls', namespace='toast')),
    url(r'^company/', include('company.urls', namespace='company')),
    url(r'^tags/', include('tags.urls', namespace='tags')),
    url(r'gallery/', include('gallery.urls', namespace='gallery')),

    url(r'^media/(?P<path>.*)$', django.views.static.serve, {'document_root': settings.MEDIA_ROOT}),

    url(r'^accounts/', include('accounts.urls', namespace='accounts')),

    url(r'^api/v1/company/', include('company.api.urls', namespace='api_company')),
    url(r'^api/v1/gallery/', include('gallery.api.urls', namespace='api_gallery'))
]

# if settings.DEBUG:
#     if settings.MEDIA_URL:
#         urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_URL)
#         urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

gallery/urls.py
from django.conf.urls import url

from .views import (
    AlbumListView,
    PhotoListView,
    PhotoAddView,
    AlbumAddView,
    AlbumUpdateView,
    AlbumDeleteView,

    PhotosListView,
)


urlpatterns = [
    url(r'^albums/$', AlbumListView.as_view(), name='albums'),
    url(r'^album/(?P<pk>\d+)/$', PhotoListView.as_view(), name='photo'),
    url(r'^photo-add/$', PhotoAddView.as_view(), name='photo_add'),
    url(r'^album/add/$', AlbumAddView.as_view(), name='album_add'),
    url(r'^album/(?P<pk>\d+)/update/$', AlbumUpdateView.as_view(), name='album_update'),
    url(r'^album/(?P<pk>\d+)/delete/$', AlbumDeleteView.as_view(), name='album_delete'),

    url(r'^photos/$', PhotosListView.as_view(), name='photos'),

    # url(r'^add/$', CompanyAddView.as_view(), name='company_add'),
    # url(r'^update/(?P<pk>\d+)/$', CompanyUpdateView.as_view(), name='company_update'),
    # url(r'^delete/(?P<pk>\d+)/$', CompanyDeleteView.as_view(), name='company_delete'),
    # url(r'^(?P<pk>\d+)/$', CompanyDetailView.as_view(), name='company_detail'),
    # url(r'^profile_update/$', ProfileCreateView.as_view(), name='profile-update'),
]

accounts/models.py
from django.db import models
from django.core.mail import send_mail
from django.core.mail import EmailMessage
from django.core.mail import EmailMultiAlternatives
from django.conf import settings
from django.template.loader import get_template
from django.core.urlresolvers import reverse
from django.utils.encoding import force_bytes, force_text
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.utils.translation import ugettext_lazy as _

from django.contrib.auth.models import (
    AbstractBaseUser,
    BaseUserManager,
    PermissionsMixin
)

from .tokens import account_activation_token

class UserManager(BaseUserManager):
    def create_user(self, email, password=None, is_active=True, is_staff=False, is_admin=False):
        """
        Creates and saves a User with the given email and password.
        """
        if not email:
            raise ValueError("Users must have an email address")
        if not password:
            raise ValueError("Users must have a password")

        user_obj = self.model(
            email=self.normalize_email(email),
        )
        user_obj.set_password(password)  # change user password
        user_obj.active = is_active
        user_obj.staff = is_staff
        user_obj.admin = is_admin
        user_obj.save(using=self._db)
        return user_obj

    def create_staffuser(self, email, password=None):
        """
        Creates and saves a staff user with the given email and password.
        """
        user = self.create_user(
            email,
            password=password,
            is_staff=True
        )
        return user

    def create_superuser(self, email, password=None):
        user = self.create_user(
            email,
            password=password,
            is_staff=True,
            is_admin=True
        )
        return user


class User(AbstractBaseUser, PermissionsMixin):
    email = models.EmailField(
        verbose_name='email address',
        max_length=255,
        unique=True
    )
    full_name = models.CharField(max_length=255, blank=True, null=True)
    is_active = models.BooleanField(default=True)  # can login
    staff = models.BooleanField(default=False)  # staff user non superuser
    admin = models.BooleanField(default=False)  #superuser
    date_joined = models.DateTimeField(_('date joined'), auto_now_add=True)
    update = models.DateTimeField(auto_now=True)

    USERNAME_FIELD = 'email'  # used as the unique identifier.
    REQUIRED_FIELDS = [] # ['full_name'] #python manage.py createsuperuser

    objects = UserManager()

    class Meta:
        verbose_name = _('user')
        verbose_name_plural = _('users')
        permissions = set()

    def __str__(self):
        return self.email

    def get_full_name(self):
        if self.full_name:
            return self.full_name
        return self.email

    def get_short_name(self):
        return self.email

    #@property
    #def is_active(self):
    #    return self.active

    @property
    def is_staff(self):
        return self.staff

    @property
    def is_superuser(self):
        return self.admin

    def send_activate(self):
        base_url = getattr(settings, 'BASE_URL')
        key_path = reverse(
            'accounts:activate',
            kwargs={
                'uidb64': urlsafe_base64_encode(force_bytes(self.id)),
                'token': account_activation_token.make_token(self)
            }
        )
        path = "{base}{path}".format(base=base_url, path=key_path)
        site_name = settings.DEFAULT_DOMAIN
        context = {
            'email': self.email,
            'path': path,
            'site_name': site_name
        }

        message_txt = get_template('accounts/email/verify.txt').render(context)
        message_html = get_template('accounts/email/verify.html').render(context)

        subject = _('Activate your account at to') + ' ' + site_name
        from_email, to = settings.EMAIL_HOST_USER, self.email

        msg = EmailMultiAlternatives(subject, message_txt, from_email, [to])
        msg.attach_alternative(message_html, "text/html")

        # email = EmailMessage(
        #     subject='Activate your account at toasters.com.',
        #     body=message_html,
        #     from_email=settings.EMAIL_HOST_USER,
        #     to=[self.email],
        # )

        return msg.send(fail_silently=False)

accounts/views.py
from django.shortcuts import render,  redirect
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth import views
from django.urls import reverse
from django.core.urlresolvers import reverse_lazy
from django.contrib import auth
from django.contrib.auth.forms import PasswordChangeForm

from django.views.generic import FormView, CreateView, DetailView, View, UpdateView
from django.utils.encoding import force_bytes, force_text
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode

from .forms import (
    LoginForm,
    RegisterForm,
    UserDetailChangeForm,
)
from django.utils.translation import ugettext as _

from django.contrib.messages.views import SuccessMessageMixin
from django.contrib.auth import update_session_auth_hash

from .tokens import account_activation_token
from .messages import ErrorMessageMixin

from company.models import Company
from gallery.models import Album

from django.contrib.auth import get_user_model

User = get_user_model()


class AccountDashboardView(LoginRequiredMixin, DetailView):
    template_name = 'accounts/dashboard.html'

    def get_object(self, queryset=None):
        return self.request.user

    def get_context_data(self, **kwargs):
        ctx = super(AccountDashboardView, self).get_context_data(**kwargs)
        try:
            ctx['companies'] = Company.objects.filter(user_id=self.get_object())
        except:
            ctx['companies'] = None

        try:
            ctx['albums'] = Album.objects.filter(user_id=self.get_object())
        except:
            ctx['albums'] = None

        ctx['title'] = _('Account')
        return ctx


class AccountActivateView(View):
    template_name = 'accounts/activate_done.html'

    def get(self, request, uidb64, token, **kwargs):
        try:
            uid = force_text(urlsafe_base64_decode(uidb64))
            user = User.objects.get(pk=uid)
        except (TypeError, ValueError, OverflowError, User.DoesNotExist):
            user = None
        if user is not None and account_activation_token.check_token(user, token):
            user.is_active = True
            user.save()

            msg = _('Thank you for your email confirmation. Now you can login your account.')
        else:
            msg = _('Activation link is invalid!')

        context = {
            'title': _('Email confirmation'),
            'msg': msg
        }
        return render(request, self.template_name, context)


class LoginView(SuccessMessageMixin,
                ErrorMessageMixin,
                FormView):

    form_class = LoginForm
    success_url = reverse_lazy('accounts:dashboard')
    template_name = 'accounts/login.html'
    default_next = '/'
    success_message = _("Login successful!")
    error_message = _('Please correct the errors below.')

    def get_form_kwargs(self):
        kwargs = super(LoginView, self).get_form_kwargs()
        kwargs['request'] = self.request
        return kwargs

    def get(self, request, *args, **kwargs):
        # if the user is authorized, then redirect to the success url
        if auth.get_user(request).is_authenticated:
            return redirect(self.success_url)
        else:
            return self.render_to_response(self.get_context_data())


class RegisterView(SuccessMessageMixin, ErrorMessageMixin, CreateView):
    form_class = RegisterForm
    template_name = 'accounts/register.html'
    success_url = '/accounts/register/done/'
    success_message = _("Account %(email)s was created successfully!")
    error_message = _('Please correct the errors below.')

    def get_context_data(self, **kwargs):
        context = super(RegisterView, self).get_context_data(**kwargs)
        context['title'] = _('Register')
        return context


class DoneRegisterView(View):
    template_name = 'accounts/register_done.html'

    def get(self, request, **kwargs):
        msg = _("Please confirm your email address  to complete the registration.")

        context = {
            'title': _("Register is done"),
            'msg': msg
        }
        return render(request, self.template_name, context)


class UserDetailUpdateView(LoginRequiredMixin,
                           SuccessMessageMixin,
                           ErrorMessageMixin,
                           UpdateView):

    form_class = UserDetailChangeForm
    success_url = reverse_lazy('accounts:dashboard')
    template_name = 'accounts/detail_update_view.html'
    success_message = _("Your account was updated successfully!")
    error_message = _('Please correct the errors below.')

    def get_object(self, queryset=None):
        return self.request.user

    def get_context_data(self, *args, **kwargs):
        context = super(UserDetailUpdateView, self).get_context_data(*args, **kwargs)
        context['title'] = _('Change Your Account Details')
        return context


class UserPasswordChangeView(LoginRequiredMixin,
                             SuccessMessageMixin,
                             ErrorMessageMixin,
                             FormView):
    form_class = PasswordChangeForm
    success_url = reverse_lazy('accounts:dashboard')
    template_name = 'accounts/change_password.html'
    success_message = _("Your password was successfully updated!")
    error_message = _('Please correct the errors below.')

    def get_form_kwargs(self):
        kwargs = super(UserPasswordChangeView, self).get_form_kwargs()
        kwargs['user'] = self.request.user
        return kwargs

    def form_valid(self, form):
        form.save()
        # Updating the password logs out all other sessions for the user
        # except the current one.
        update_session_auth_hash(self.request, form.user)
        return super(UserPasswordChangeView, self).form_valid(form)

    def get_context_data(self, *args, **kwargs):
        context = super(UserPasswordChangeView, self).get_context_data(*args, **kwargs)
        context['title'] = _('Password change')
        return context

accounts/templates/accounts/activate_done.html
{% extends  'core/base.html' %}
{% load i18n %}

{% block title %}
    {{ title }}
{% endblock %}

{% block content  %}
<div class="row">
    {{ msg }}
</div>
{% endblock %}

accounts/templates/accounts/change_password.html
{% extends  'core/base.html' %}
{% load i18n %}

{% block title %}
    {{ title }}
{% endblock %}

{% block content %}
    <div class="grid-x">
        <div class="cell small-12 medium-5 large-4 float-center">
            <div class="card-form">
                <div class="card-divider">
                    {% if title %}<h4 class=''>{{ title }}</h4>{% endif %}
                </div>
                <div class="card-section">
                    <form data-abide novalidate method="post">
                        {% csrf_token %}
                        {{ form.as_table }}
                        <button type='submit' class='button success small expanded'>{% trans "Save changes" %}</button>
                        <a class="button secondary small hollow expanded" href="{% url 'accounts:dashboard' %}">{% trans "Cancel" %}</a>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

accounts/templates/accounts/dashboard.html
{% extends 'core/base.html' %}
{% load i18n %}

{% block title %}
    {{ title }}
{% endblock %}

{% block content %}
    <div class="grid-x grid-margin-x">
        <div class="cell small-12 medium-4 large-4 float-left">
            <div class="card">
                <h4 class="card-divider">{% trans "Account Details" %}</h4>
                <ul class="card-section no-bullet">
                    {% if user.full_name %}
                        <li>{{ user.full_name }}</li>
                    {% endif %}
                    <li>{{ user.email }}</li>
                    <li><a href='{% url "accounts:user-update" %}'>
                        <i class="fa fa-pencil-alt fa-lg" style="color: darkblue;"></i>&nbsp;
                        {% trans "Update Account Details" %}</a></li>
                    <li><a href='{% url "accounts:change_password" %}'>
                        <i class="fas fa-exchange-alt fa-lg" style="color: blueviolet;"></i>&nbsp;
                        {% trans "Change Password" %}</a></li>
                </ul>
            </div>
        </div>
        <div class='cell small-12 medium-4 large-4 float-left'>
            <div class="card">
                <h4 class="card-divider">{% trans "Your company" %}</h4>
                <ul class="card-section no-bullet">
                    {% if user.is_staff %}
                        <li>
                            <a href='{% url "admin:company_company_changelist" %}'>{% trans "List of companies" %}</a>
                        </li>
                    {% else %}
                        {% if companies.count > 0 %}
{#                                                <ul >#}
                            <li class="subheader ">{% trans "Company" %}: {{ companies.0 }}</li>
                            <ul class="no-bullet">
                                <li>
                                    <a href='{% url "company:company_detail" companies.0.id %}'>{% trans "View company" %}</a>
                                </li>
                                <li>
                                    <a href='{% url "company:company_update" companies.0.id %}'>{% trans "Update company" %}</a>
                                </li>
                                <li>
                                    <a href='{% url "company:company_delete" companies.0.id %}'>{% trans "Delete company" %}</a>
                                </li>
                            </ul>
                            {#                    </ul>#}
                        {% else %}
                            <li><a href='{% url "company:company_add" %}'>
                                <i class="fas fa-plus fa-lg" style="color: green;"></i>&nbsp;
                                {% trans "Add company" %}</a></li>
                        {% endif %}
                    {% endif %}

                </ul>
            </div>
        </div>
        <div class='cell small-12 medium-4 large-4 float-left'>
            <div class="card">
                <h4 class="card-divider">{% trans "Gallery" %}</h4>
                <ul class="card-section no-bullet">
                    <li><a href='{% url "gallery:photo_add" %}'>
                        <i class="fas fa-plus fa-lg" style="color: green;"></i>&nbsp;
                        {% trans "Add photo" %}</a></li>
                    <li><a href='{% url "gallery:album_add" %}'>
                        <i class="fas fa-plus fa-lg" style="color: green;"></i>&nbsp;
                        {% trans "Create album" %}</a></li>

{#                    {{ albums }}#}
                    {% for album in albums %}
{#                        {{ album }}#}
{#                        {{ album.id }}#}


                        <li><a href='{% url "gallery:album_update" pk=album.id %}'>
                            <i class="fas fa-exchange-alt fa-lg" style="color: blueviolet;"></i>&nbsp;{{ album }}
                            {% trans "Update album" %}</a>
                        </li>

                    {% endfor %}
                </ul>
            </div>
        </div>
    </div>
{% endblock %}

accounts/templates/accounts/detail_update_view.html
{% extends 'core/base.html' %}
{% load i18n %}

{% block title %}
    {{ title }}
{% endblock %}

{% block content %}
    <div class="grid-x">
        <div class="cell small-9 medium-5 large-4 float-center">
            <div class="card">
                <div class="card-divider">
                    {% if title %}<h4 class=''>{{ title }}</h4>{% endif %}
                </div>
                <div class="card-section">
                    <form method='POST' action='{% if action_url %}{{ action_url }}{% endif %}'> {% csrf_token %}
                        {% if next_url %}
                            <input type='hidden' name='next' value='{{ next_url }}'/>
                        {% endif %}
                        {{ form.as_p }}
                        <button type='submit' class='button success small expanded'>{% trans "Save" %}</button>
                        <a class="button secondary small hollow expanded" href="{% url 'accounts:dashboard' %}">{% trans "Cancel" %}</a>
                        <a class='button small expanded'
                           href='{% url "accounts:change_password" %}'>{% trans "Change Password" %}</a>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

accounts/templates/accounts/home.html
{% extends 'core/base.html' %}
{% load i18n %}

{% block title %}
    {{ title }}
{% endblock %}

{% block content %}
    <div class="grid-x grid-margin-x grid-margin-y">
        <div class="cell small-12 medium-4 large-4 float-left">
            <div class="card">
                <h4 class="card-divider">{% trans "Account Details" %}</h4>
                <ul class="card-section no-bullet">
                    {% if user.full_name %}
                        <li>{{ user.full_name }}</li>
                    {% endif %}
                    <li>{{ user.email }}</li>
                    {% if company %}
                        <li>{% trans "Company" %}: {{ company.name }}</li>
                    {% endif %}
                    <li><a href='{% url "accounts:user-update" %}'>
                        <i class="fa fa-pencil-alt fa-lg" style="color: darkblue;"></i>&nbsp;
                        {% trans "Update Account Details" %}</a></li>
                    <li><a href='{% url "accounts:change_password" %}'>
                        <i class="fas fa-exchange-alt fa-lg" style="color: blueviolet;"></i>&nbsp;
                        {% trans "Change Password" %}</a></li>
                </ul>
            </div>
        </div>
        <div class='cell small-12 medium-4 large-4 float-left'>
            <div class="card">
                <h4 class="card-divider">{% trans "Your company" %}</h4>
                <ul class="card-section no-bullet">
                    {% if user.is_staff %}
                        <li>
                            <a href='{% url "admin:company_company_changelist" %}'>{% trans "List of companies" %}</a>
                        </li>
                    {% else %}
                        {% if companies.count > 0 %}
{#                                                <ul >#}
                            <li class="subheader ">{% trans "Company" %}: {{ companies.0 }}</li>
                            <ul class="no-bullet">
                                <li>
                                    <a href='{% url "company:company_detail" companies.0.id %}'>{% trans "View company" %}</a>
                                </li>
                                <li>
                                    <a href='{% url "company:company_update" companies.0.id %}'>{% trans "Update company" %}</a>
                                </li>
                                <li>
                                    <a href='{% url "company:company_delete" companies.0.id %}'>{% trans "Delete company" %}</a>
                                </li>
                            </ul>
                            {#                    </ul>#}
                        {% else %}
                            <li><a href='{% url "company:company_add" %}'>
                                <i class="fas fa-plus fa-lg" style="color: green;"></i>&nbsp;
                                {% trans "Add company" %}</a></li>
                        {% endif %}
                    {% endif %}

                </ul>
            </div>
        </div>
        <div class='cell small-12 medium-4 large-4 float-left'>
            <div class="card">
                <h4 class="card-divider">{% trans "Gallery" %}</h4>
                <ul class="card-section no-bullet">
                    <li><a href='{% url "gallery:photo_add" %}'>
                        <i class="fas fa-plus fa-lg" style="color: green;"></i>&nbsp;
                        {% trans "Add photo" %}</a></li>
                    <li><a href='{% url "gallery:album_add" %}'>
                        <i class="fas fa-plus fa-lg" style="color: green;"></i>&nbsp;
                        {% trans "Add album" %}</a></li>

{#                    {{ albums }}#}
                    {% for album in albums %}
{#                        {{ album }}#}
{#                        {{ album.id }}#}


                        <li><a href='{% url "gallery:album_update" pk=album.id %}'>
                            <i class="fas fa-exchange-alt fa-lg" style="color: blueviolet;"></i>&nbsp;{{ album }}
                            {% trans "Update album" %}</a>
                        </li>

                    {% endfor %}
                </ul>
            </div>
        </div>
    </div>
{% endblock %}

accounts/templates/accounts/login.html
{% extends 'core/base.html' %}
{% load i18n %}

{% block title %}
    {% trans "Log in" %}
{% endblock %}

{% block content %}
    <div class="grid-x">
        <div class="cell small-12 medium-6 large-5 float-center">
            <div class="card">
                <div class="card-divider">
                    <h4>{% trans "Log in" %}</h4>
                </div>
{#                            <img src="{{ MEDIA_URL }}img_site/765887.jpg" alt="" class="card-image">#}
                <div class="card-section">
                    <form data-abide novalidate action="." method="post">{% csrf_token %}
                        <!-- Add "display: none" right away -->
{#                        <div data-abide-error class="alert callout" style="display: none;">#}
{#                          <p><i class="fi-alert"></i> There are some errors in your form.</p>#}
{#                        </div>#}

                        {% for error in form.non_field_errors %}
                            <div class="alert callout">
                                {{ error|escape }}
                            </div>
                        {% endfor %}
                        <div>
                            {{ form.email.errors }}
                            {{ form.email.label_tag }} {{ form.email }}
                        </div>
                        <div>
                            {{ form.password.errors }}
                            {{ form.password.label_tag }} {{ form.password }}
                        </div>
                        <div class="form-row">
                            {{ form.remember_me.errors }}
                            {{ form.remember_me }} {{ form.remember_me.label_tag }}
                        </div>
                        <a href="{% url 'accounts:password_reset' %}">{% trans "Forgotten your password?" %}</a>
                        <button type='submit' class='button success small expanded'>{% trans "Log in" %}</button>
                        <a class="button small expanded" href="{% url 'accounts:register' %}">{% trans 'Register' %}</a>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

accounts/templates/accounts/register.html
{% extends 'core/base.html' %}
{% load i18n %}

{% block title %}
    {{ title }}
{% endblock %}

{% block content %}
    <div class="grid-x">
        <div class="cell small-12 medium-6 large-5 float-center">
            <div class="card">
                <div class="card-divider">
                    <h4>{{ title }}</h4>
                </div>
                <div class="card-section">
                    <form data-abide novalidate action="." method="post">{% csrf_token %}
                        {% for error in form.non_field_errors %}
                            <div class="alert callout">
                                {{ error|escape }}
                            </div>
                        {% endfor %}
                        <div>
                            {{ form.email.errors }}
                            {{ form.email.label_tag }} {{ form.email }}
                        </div>
                        <div>
                            {{ form.password1.errors }}
                            {{ form.password1.label_tag }} {{ form.password1 }}
                            <div class="help-text">{{ form.password1.help_text|safe }}</div>
                        </div>
                        <div>
                            {{ form.password2.errors }}
                            {{ form.password2.label_tag }} {{ form.password2 }}
                            <p class="help-text">{{ form.password2.help_text }}</p>
                        </div>
                        <button class="button success small expanded" type="submit" value="{{ title }}">{{ title }}</button>
                        <a class="button secondary hollow small expanded" href="{% url 'company:companies' %}">{% trans "Cancel" %}</a>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

accounts/templates/accounts/register_done.html
{% extends  'core/base.html' %}
{% load i18n %}

{% block title %}
    {{ title }}
{% endblock %}

{% block content  %}
<div class="row column">
    {{ msg }}
</div>
{% endblock %}