company/urls.py
from django.conf.urls import url

from .views import (
    CompanyListView,
    CompanyAddView,
    CompanyDetailView,
    CompanyUpdateView,
    CompanyDeleteView,
    # CompanyCreate
)

urlpatterns = [
    # url(r'^$', CompanyListView.as_view(), name='companies'),
    url(r'^filter/(?P<location>[a-z\-]+)?/?(?P<type>[a-z\-]+)?/?(?P<price>[a-z0-9\-]+)?/?$', CompanyListView.as_view(), name='companies'),
    # url(r'^toaster/$', CompanyListView.as_view(), name='companies'),
    url(r'^add/$', CompanyAddView.as_view(), name='company_add'),
    # url(r'^add/$', CompanyCreate.as_view(), name='company_add'),
    url(r'^update/(?P<pk>\d+)/$', CompanyUpdateView.as_view(), name='company_update'),
    url(r'^delete/(?P<pk>\d+)/$', CompanyDeleteView.as_view(), name='company_delete'),
    url(r'^(?P<pk>\d+)/$', CompanyDetailView.as_view(), name='company_detail'),
    # url(r'^profile_update/$', ProfileCreateView.as_view(), name='profile-update'),
]

core/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf.urls.static import static

import django.views.static
from django.conf import settings


urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^ckeditor/', include('ckeditor_uploader.urls')),
    # url(r'^toasters/', include('toast.urls', namespace='toast')),
    url(r'^company/', include('company.urls', namespace='company')),
    url(r'^tags/', include('tags.urls', namespace='tags')),
    url(r'gallery/', include('gallery.urls', namespace='gallery')),

    url(r'^media/(?P<path>.*)$', django.views.static.serve, {'document_root': settings.MEDIA_ROOT}),

    url(r'^accounts/', include('accounts.urls', namespace='accounts')),

    url(r'^api/v1/company/', include('company.api.urls', namespace='api_company')),
    url(r'^api/v1/gallery/', include('gallery.api.urls', namespace='api_gallery'))
]

# if settings.DEBUG:
#     if settings.MEDIA_URL:
#         urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_URL)
#         urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

tags/urls.py
from django.conf.urls import url

from .views import (
    TagListView,
    TagDetailView,
)

urlpatterns = [
    url(r'list/$', TagListView.as_view(), name='tag_list'),
    url(r'^(?P<slug>[-\w]+)/$', TagDetailView.as_view(), name='tag_detail'),
]

tags/models.py
from django.db import models
from django.utils.translation import ugettext as _

from core.models_abstract import MainAbstractModel


class Tag(MainAbstractModel):
    name = models.CharField(max_length=120, unique=True, verbose_name=_('Tag name'))
    slug = models.SlugField(max_length=140, blank=True, null=True)

    class Meta:
        verbose_name = _('Tag')
        verbose_name_plural = _('Tags')

tags/views.py
from django.shortcuts import render
from django.views.generic import ListView, DetailView

from .models import Tag
from company.models import Company


class TagListView(ListView):
    model = Tag

    def get_context_data(self, **kwargs):
        context = super(TagListView, self).get_context_data(**kwargs)
        context.update({'tags': Tag.objects.all()})
        return context


class TagDetailView(DetailView):
    model = Tag
    slug_field = 'slug'

    def get_context_data(self, **kwargs):
        context = super(TagDetailView, self).get_context_data(**kwargs)
        context.update({'companies': Company.objects.filter(tags=Tag.objects.get(slug=self.object.slug))})
        return context

tags/templates/tags/tag_detail.html
{% extends 'core/base.html' %}
{% load i18n %}

{% block title %}
    {{ tag.name }}
{% endblock %}

{#{% block header %}#}
{#    <h1 class="subheader">{{ toaster.name }}</h1>#}
{#{% endblock %}#}

{% block content %}
    <div class="row">
        <h3>{{ tag.name }}</h3>

        <ul class="column">
            {% for company in companies %}
                <li><a href="{% url 'company:company_detail' pk=company.id %}">{{ company }}</a></li>
            {% endfor %}
        </ul>
    </div>
{% endblock %}

tags/templates/tags/tag_list.html
{% extends 'core/base.html' %}

{% block title %}
    List of tags
{% endblock %}

{% block header %}
    <h1 class="subheader">List of tags</h1>
{% endblock %}

{% block content %}
    <div class="row">
        <ul class="column">
            {% for tag  in tags %}
                <li><a href="{% url 'tags:tag_detail' slug=tag.slug %}">{{ tag }}</a></li>
            {% endfor %}
        </ul>
    </div>
{% endblock %}